### ISSUE TITLE
登录页面无法登陆，显示登录失败

### ISSUE THREAD

**Issue by mikecyy** [ZHENFENG13/spring-boot-projects#113]
项目运行成功，出现登录页面，使用的是默认用户名和密码，但是登录失败，不知道怎么回事，是因为代码本身不是开放的吗？

**Comment by xiaoobangg** [comment]
代码是开放的，账号密码admin/admin 或者admin/123456



1393459634@qq.com
 
发件人： mikecyy
发送时间： 2019-07-27 19:42
收件人： ZHENFENG13/spring-boot-projects
抄送： Subscribed
主题： [ZHENFENG13/spring-boot-projects] 登录页面无法登陆，显示登录失败 (#113)
项目运行成功，出现登录页面，使用的是默认用户名和密码，但是登录失败，不知道怎么回事，是因为代码本身不是开放的吗？

**Comment by mikecyy** [comment]
输入admin、123456，进不去，不知道为什么，已经在mysql建了表tb_admin_user，是空的，需要往里面添加数据吗

**Comment by xiaoobangg** [comment]
我记得有个sql的初始化脚本，里面有初始的账号密码。我已经不记得了



1393459634@qq.com
 
发件人： mikecyy
发送时间： 2019-07-27 20:07
收件人： ZHENFENG13/spring-boot-projects
抄送： xiaoobangg; Comment
主题： Re: [ZHENFENG13/spring-boot-projects] 登录页面无法登陆，显示登录失败 (#113)
输入admin、123456，进不去，不知道为什么，已经在mysql建了表tb_admin_user，是空的，需要往里面添加数据吗

**Comment by mikecyy** [comment]
好的我去试试，非常感谢！


------------------


Hi，this is Mike，here is my mail，thank you for your reading!!!


 




------------------ 原始邮件 ------------------
发件人: "xiaoobangg"<notifications@github.com>;
发送时间: 2019年7月27日(星期六) 晚上8:12
收件人: "ZHENFENG13/spring-boot-projects"<spring-boot-projects@noreply.github.com>;
抄送: "Mike 源毅"<1481150782@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ZHENFENG13/spring-boot-projects] 登录页面无法登陆，显示登录失败 (#113)



我记得有个sql的初始化脚本，里面有初始的账号密码。我已经不记得了 
 
 
 
 1393459634@qq.com 
   
 发件人： mikecyy 
 发送时间： 2019-07-27 20:07 
 收件人： ZHENFENG13/spring-boot-projects 
 抄送： xiaoobangg; Comment 
 主题： Re: [ZHENFENG13/spring-boot-projects] 登录页面无法登陆，显示登录失败 (#113) 
 输入admin、123456，进不去，不知道为什么，已经在mysql建了表tb_admin_user，是空的，需要往里面添加数据吗

**Comment by mikecyy** [comment]
执行过springboot-project-schema.sql脚本后，登录成功，厉害了

**Comment by baozaoxiaoli** [comment]
想问下后台登录页面怎么打开的呀.....我打开路径好像不太对....

**Comment by mikecyy** [comment]
This is an automatic reply, confirming that your e-mail was received.Thank you！Mike will get back to you as soon as possible！

**Comment by ThorinChen** [comment]
您好，我已收到您的邮件，尽快给您回复。
