### ISSUE TITLE
为啥同一个条件要用或检查两遍

### ISSUE THREAD

**Issue by remiliacn** [ZHENFENG13/spring-boot-projects#123]
读示例代码读到这里没看懂

https://github.com/ZHENFENG13/spring-boot-projects/blob/4abe8199a964c8fa71712230af4bf82ebd51c9fd/SpringBoot%E5%85%A5%E9%97%A8%E6%A1%88%E4%BE%8B%E6%BA%90%E7%A0%81/spring-boot-ajax/src/main/java/com/lou/springboot/controller/RequestTestController.java#L18

**Comment by ZHENFENG13** [comment]
写错了
